apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: products-destination
spec:
  host: products-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80
