apiVersion: v1
kind: Pod
metadata:
  name: istio-test
spec:
  containers:
    - name: istio-test
      image: volodymyrmushii/istio-check:latest
      imagePullPolicy: Always
      env:
        - name: URL
          value: "http://products-service:80/products/"
        - name: NUM_REQUESTS
          value: "10"
