apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      initContainers:
          - name: run-migrations
            image: volodymyrmushii/products-migration:latest
            imagePullPolicy: Always
            command: ["./node_modules/.bin/node-pg-migrate", "up"]
            env:
              - name: DATABASE_URL
                value: "postgres://demo:demo@postgres-products:5432/demo-products"
      containers:
        - name: products
          image: volodymyrmushii/products:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080