apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: products-virtual
spec:
  hosts:
    - products-service
  http:
    - route:
        - destination:
            host: products-service
      timeout: 1s
      retries:
        attempts: 1
        retryOn: 5xx
        perTryTimeout: 2s
