apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sellers-virtual
spec:
  hosts:
    - sellers-service
  http:
    - route:
        - destination:
            host: sellers-service
      timeout: 5s
      retries:
        attempts: 3
        retryOn: 5xx
        perTryTimeout: 5s
